### ISSUE TITLE
pip installable version 

### ISSUE THREAD

**Issue by wjs20** [oxpig/ANARCI#12]
Hi oxpig team

Is there a pip installable version of anarci? Thanks

**Comment by broncio123** [comment]
Not to my knowledge. Provisionally you can try this via terminal 

```bash
git clone https://github.com/oxpig/ANARCI.git
cd ANARCI
python setup.py --user #if no root user
pip install -r requirements.txt
```
I'll close the issue.

**Comment by prihoda** [comment]
@broncio123 @wjs20 You can also use `pip install git+https://github.com/oxpig/ANARCI`. This also works in requirements.txt. Just keep in mind that you also need HMMER installed.

**Comment by prihoda** [comment]
@broncio123 are you considering putting ANARCI up on pypi? It would enable creating more pypi packages that use ANARCI as a dependency. You could use `pyhmmer` to avoid depending on hmmer binaries https://github.com/althonos/pyhmmer
