### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by guyujun** [oxpig/ANARCI#2]
type error, if using ANARCI local version.

i use this sequence:
QVQLVQSGAEVKRPGASVKVSCKASGYTFTNDIIHWVRQAPGQRLEWMGWINAGYGNTQYSQNFQDRVSITRDTSASTAYMELISLRSEDTAVYYCAREPLWFGESSPHDYYGMDVWGQGTTVTVS

Error: Something really went wrong that has not been handled
string indices must be integers
<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'> Error:  string indices must be integers

cmd:
ANARCI -i QVQLVQSGAEVKRPGASVKVSCKASGYTFTNDIIHWVRQAPGQRLEWMGWINAGYGNTQYSQNFQDRVSITRDTSASTAYMELISLRSEDTAVYYCAREPLWFGESSPHDYYGMDVWGQGTTVTVS --restrict heavy

**Comment by jwillis-twist** [comment]
@guyujun what version of python are you using?

**Comment by broncio123** [comment]
I have tested the above command and ANARCI works fine. 
I'll close this issue since no apparent error has been replicated with ANARCI latest version 13 December 2021.
