### ISSUE TITLE
Inconsistent licensing

### ISSUE THREAD

**Issue by merkys** [oxpig/ANARCI#32]
Thank you for developing this useful piece of F/LOSS. While evaluating the terms of use of ANARCI, I have noticed there are mentions of at least two different licenses:

1. File `LICENCE` contains the text of [BSD-3-Clause license](https://spdx.org/licenses/BSD-3-Clause.html), seemingly declaring single all-governing license for the project;
2. File `bin/ANARCI` and couple others contain the text of [GPL-3-or-later license](https://spdx.org/licenses/GPL-3.0-or-later.html). The same executable also prints text "Freely distributed under the GNU General Public License (GPLv3)" which is slightly different from aforementioned GPL-3-or-later.

In addition, it should probably be mentioned that files under `build_pipeline/IMGT_sequence_files/` are licensed as [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/) and, strictly speaking, renders the whole package usable for non-commercial uses only (as per [IMGT terms of use](https://www.imgt.org/about/termsofuse.php)).

**Comment by merkys** [comment]
Is there any update regarding this issue? I find this piece of software tremendously useful, and would like to package it for Debian to simplify its installation for Debian/Ubuntu users (including me and my students).

**Comment by FBoyles** [comment]
@merkys Thanks for flagging this - the software was re-licenced under BSD 3-Clause some time ago; references to GPL-3 have now been removed.
