### ISSUE TITLE
submodule_search_location installation issues

### ISSUE THREAD

**Issue by jadolfbr** [oxpig/ANARCI#44]
Hello,

When I try to install ANARCI on a linux machine, I get the following after running
`python setup.py install --user`

Has this been seen before?  Are there any fixes or suggestions for this issue? Thanks.
```
Writing /home/jadolfbr/.local/lib/python3.6/site-packages/anarci-1.3-py3.6.egg-info
Traceback (most recent call last):
  File "setup.py", line 38, in <module>
    ANARCI_LOC = importlib.util.find_spec("anarci").submodule_search_locations[0]
AttributeError: 'NoneType' object has no attribute 'submodule_search_locations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 40, in <module>
    sys.stderr.write(e.message)
AttributeError: 'AttributeError' object has no attribute 'message'
```

**Comment by LivC93** [comment]
Same issue

**Comment by Draught3d** [comment]
This looks like it's caused by using `importlib.util` after importing only the parent module `importlib`. Changing the import at the top of setup.py to `importlib.util` instead fixes the issue. I'll create a pull request adding that in a minute.
