### ISSUE TITLE
germlines

### ISSUE THREAD

**Issue by awesome-crab** [oxpig/ANARCI#54]
Hello everyone,

I was wondering why the germlines.py file was deleted?
But I saw in the anarci.py file we still import from .germlines ?

Could anyone give me some insight?

Best regards

**Comment by FBoyles** [comment]
We are unable to distribute IMGT data directly with the code as this contradicts the IMGT terms of use. Instead, germline data is downloaded during the installation process.

**Comment by awesome-crab** [comment]
Thank you very much for the info!
Have a great day!
