### ISSUE TITLE
can not use in win10, need help

### ISSUE THREAD

**Issue by qiuqingpo** [oxpig/ANARCI#55]
the error is below:

> running install
> C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> running build
> running build_py
> running egg_info
> writing anarci.egg-info\PKG-INFO
> writing dependency_links to anarci.egg-info\dependency_links.txt
> writing top-level names to anarci.egg-info\top_level.txt
> reading manifest file 'anarci.egg-info\SOURCES.txt'
> adding license file 'LICENCE'
> adding license file 'LICENCE_MUSCLE'
> writing manifest file 'anarci.egg-info\SOURCES.txt'
> running build_scripts
> running install_lib
> running install_data
> running install_egg_info
> removing 'C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\Lib\site-packages\anarci-1.3-py3.10.egg-info' (and everything under it)
> Copying anarci.egg-info to C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\Lib\site-packages\anarci-1.3-py3.10.egg-info
> running install_scripts
> INFO: ANARCI lives in:  C:\Users\qiuqingpo\AppData\Local\Programs\Python\Python310\anarci
> INFO: Downloading germlines from IMGT and building HMMs...
> INFO: running 'RUN_pipeline.sh', this will take a couple a minutes.
> ??? Linux ? Windows ?????????????
> ?????? Microsoft Store ??????:
> https://aka.ms/wslstore
> 
> 
> error: [Errno 2] No such file or directory: 'curated_alignments/germlines.py'

_**some one who tell me need to install  HMMER3 version 3.1 higher,**_
**but i see my localhost, my version is v0.2.3, the most important thing is that: i can not install the hmmer 3.1 or higher, please help!**

**Comment by awesome-crab** [comment]
maybe try using it in docker. that would leave you independent of your os.

Generally I think the issue you have is that HMMER is not working on Windows.
In order to install HMMER on your windows10 machine, you would have to install WSL2. And then you would be able to install HMMER on WSL2 on your windows10. 

Either way you decide you will have to install WSL2. BEcause docker is also relying on WSL...

Hope that helps a little bit.

**Comment by qiuqingpo** [comment]
thank you very much, it's important for me!
