### ISSUE TITLE
can I use it to do "cdr annotation"? how to do it, tell me some suggestions 

### ISSUE THREAD

**Issue by qiuqingpo** [oxpig/ANARCI#56]
can I use it to do "cdr annotation"? how to do it, tell me some suggestions, thank you!

**Comment by qiuqingpo** [comment]
I'm sorry, I'm not a biology major, and I don't understand imgt's instructions very well, but I'm looking forward to your's ANARCI adding the cdr annotation,  thank you

**Comment by awesome-crab** [comment]
I am not a biology major either. I just read the stuff which I need to know. Some stuff you will learn on the way. 
Maybe just to point out. ANARCI will try to detect a domain (in simplest terms a variable region) inside the Antibody sequence with help of Hidden Markov Models.
The domain will then be annotated (numbered) with the numbering scheme you specified when running ANARCI. Depending on the numbering scheme, the cdrs are at certain positions. Within IMGT the cdr1 is always from pos 27 to pos 38. Similar with the other cdrs. I just wanted to make this clear as I was not sure if my answer before was clear. Also before I stated that in IMGT the cdr1 is from 26 to 39 which is not correct. One could consider 26 and 39 to be the anchor points. 
Remember the 4th of june!! Its an important day for students....

**Comment by qiuqingpo** [comment]
> I am not a biology major either. I just read the stuff which I need to know. Some stuff you will learn on the way. Maybe just to point out. ANARCI will try to detect a domain (in simplest terms a variable region) inside the Antibody sequence with help of Hidden Markov Models. The domain will then be annotated (numbered) with the numbering scheme you specified when running ANARCI. Depending on the numbering scheme, the cdrs are at certain positions. Within IMGT the cdr1 is always from pos 27 to pos 38. Similar with the other cdrs. I just wanted to make this clear as I was not sure if my answer before was clear. Also before I stated that in IMGT the cdr1 is from 26 to 39 which is not correct. One could consider 26 and 39 to be the anchor points. Remember the 4th of june!! Its an important day for students....

hello, i see the issues, and find have the  get_imgt_cdr function, but have errors ,Will it affect?
https://github.com/oxpig/ANARCI/issues/14

**Comment by qiuqingpo** [comment]
> i do not understand your question. try being more specific.

Can ANARCI  use to get cdrs by imgt? I found the function "get_imgt_cdr ".

**Comment by awesome-crab** [comment]
I already told you yes. I pointed out above how you can achieve this. I don't know where you found "get_imgt_cdr" but I dont think it is from the ANARCI repository. So maybe go to the repo from where you have your function?

**Comment by qiuqingpo** [comment]
Sorry,i just know it, if I want to use Chothia, Kabat, or  Contact to cdr annotation, can you give me some documents,
as like [](https://www.imgt.org/IMGTScientificChart/Numbering/IMGTnumberingCDR_VH.html)

**Comment by qiuqingpo** [comment]
@awesome-crab hello, my dear, thank you for your heat reply, i check the code, find get database from the imgt website use RipIMGT.py, url is follow:

urls = { "HV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHV&species=%s",
         "HJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGHJ&species=%s",
         "KV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKV&species=%s",
         "KJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGKJ&species=%s",
         "LV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLV&species=%s",
         "LJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGLJ&species=%s",
         "AV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRAV&species=%s",
         "AJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRAJ&species=%s",
         "BV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRBV&species=%s",
         "BJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRBJ&species=%s",
         "GV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRGV&species=%s",
         "GJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRGJ&species=%s",
         "DV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRDV&species=%s",
         "DJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRDJ&species=%s"
         
         #"HC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHC&species=%s",
         #"KC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKC&species=%s",
         #"LC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLC&species=%s",
       }
**but the imgt website update very often, need i reinstall the ANARCI again? Can ANARCI get the imgt data automatic? thank you!**

**Comment by awesome-crab** [comment]
Yeah, sorry I am not going to answer you anymore. It seems you do not understand english well enough to understand the answers I gave. Good luck.

**Comment by awesome-crab** [comment]
It seems you do not understand what you are doing also I have no idea what you do with RipIMGT.py. 
Why do you ask a question about code you found on IMGT in the github repo for ANARCI? 
Ask your question on where you got your code?!? This is ridicoulus.

**Comment by qiuqingpo** [comment]
@awesome-crab please check the file of  ANACRI's setup.py, it need run "RUN_pipeline.sh",  in the behind, there is a shell script "
python3 $DIR/RipIMGT.py", it will download data from imgt website.

**Comment by awesome-crab** [comment]
tian men square massacre1984

**Comment by qiuqingpo** [comment]
@awesome-crab I ask a new quession in https://github.com/oxpig/ANARCI/issues/63, welcome you to answer, thank you very much again

**Comment by broncio123** [comment]
> read the docs! Also, maybe read what numbering schemes are for antibodies.
> 
> ANARCI will produce a numbering of your provided Antibody sequence. depending on the numbering scheme you specified the numbering of the antibody will differ. Assuming you use IMGT: https://www.imgt.org/IMGTScientificChart/Numbering/IMGTnumberingCDR_VH.html
> 
> The cdrs are always on the same positions in the imgt numbering scheme. so in imgt cdr1 will be numbers 26 to 39.

Sorry guys, I will close this issue, as the answer provided by @awesome-crab is actually good enough, plus, this question is not software-related. Also, already addressed issue #63 . Please, see answer there.
