### ISSUE TITLE
README awfully difficult to read

### ISSUE THREAD

**Issue by ayansengupta17** [oxpig/ANARCI#57]
Hi Authors,

Is there any reason the README is written in this particular format? I found it awfully painful to read this. I am attaching a screenshot as well.
<img width="922" alt="Screenshot 2023-06-07 at 7 52 18 PM" src="https://github.com/oxpig/ANARCI/assets/14333284/dc4e8992-661c-4c90-9d18-544fd0d3a0af">

**Comment by FBoyles** [comment]
Yes - it's plaintext, not markdown. It was written a long time ago in a galaxy far away where it was primarily intended to be read in a text editor or displayed on a command line. We may create a markdown version in the future, but it's not a priority.
