### ISSUE TITLE
Need I reinstall ANARCI again when the website update

### ISSUE THREAD

**Issue by qiuqingpo** [oxpig/ANARCI#63]
i check the code, find get database from the imgt website use RipIMGT.py, url is follow:

urls = { "HV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHV&species=%s",
"HJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGHJ&species=%s",
"KV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKV&species=%s",
"KJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGKJ&species=%s",
"LV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLV&species=%s",
"LJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGLJ&species=%s",
"AV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRAV&species=%s",
"AJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRAJ&species=%s",
"BV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRBV&species=%s",
"BJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRBJ&species=%s",
"GV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRGV&species=%s",
"GJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRGJ&species=%s",
"DV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRDV&species=%s",
"DJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRDJ&species=%s"

     #"HC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHC&species=%s",
     #"KC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKC&species=%s",
     #"LC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLC&species=%s",
   }
### **but the imgt website update very often, need i reinstall the ANARCI again? Can ANARCI get the imgt data automatic? thank you!**

**Comment by broncio123** [comment]
> i check the code, find get database from the imgt website use RipIMGT.py, url is follow:
> 
> urls = { "HV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHV&species=%s", "HJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGHJ&species=%s", "KV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKV&species=%s", "KJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGKJ&species=%s", "LV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLV&species=%s", "LJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+IGLJ&species=%s", "AV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRAV&species=%s", "AJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRAJ&species=%s", "BV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRBV&species=%s", "BJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRBJ&species=%s", "GV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRGV&species=%s", "GJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRGJ&species=%s", "DV": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+TRDV&species=%s", "DJ": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.6+TRDJ&species=%s"
> 
> ```
>  #"HC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGHC&species=%s",
>  #"KC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGKC&species=%s",
>  #"LC": "http://www.imgt.org/IMGT_GENE-DB/GENElect?query=7.3+IGLC&species=%s",
> ```
> 
> }
> 
> ### **but the imgt website update very often, need i reinstall the ANARCI again? Can ANARCI get the imgt data automatic? thank you!**

Dear @qiuqingpo 

We spotted this change in the IMGT URLs last week, the latest version of ANARCI on the master branch has this fix.

If you want to update the HMMs that ANARCI uses with the latest IMGT data, then, yes pull the latest changes and reinstall again. 

However, if you have been numbering sequences with consistently human+mouse fixed as species, it is unlikely that you will see a significant change in ANARCI numbering from previous ANARCI versions, as for these species germlines are relatively stable.

I will close this issue as the above problem with URLs has now been addressed.

**Comment by qiuqingpo** [comment]
Dear @broncio123 
I see the Code you updated, the  IMGT URLs was changed,  ANARCI can rip IMGT data when it Installs. if the IMGT Data update later, can our programme update automatic? thank you!
